import { WidgetDefinition } from "./types";

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    type: "analog-clock",
    name: "Relógio Analógico",
    category: "time",
    icon: "🕐",
    description: "Mostrador circular clássico estilo Windows 7 Gadget, ponteiros suaves e opções de temas.",
    defaultWidth: 240,
    defaultHeight: 240,
    minWidth: 180,
    minHeight: 180,
    resizable: true,
    tags: ["relógio", "tempo", "aero", "ponteiros", "gadget", "horas"],
  },
  {
    type: "digital-clock",
    name: "Relógio Digital & Data",
    category: "time",
    icon: "⏰",
    description: "Horário em números grandes, segundos em tempo real, dia da semana e data completa em português.",
    defaultWidth: 260,
    defaultHeight: 140,
    minWidth: 200,
    minHeight: 100,
    resizable: true,
    tags: ["relógio", "digital", "data", "calendário", "tempo", "segundos"],
  },
  {
    type: "calendar",
    name: "Calendário Folhinha",
    category: "time",
    icon: "📅",
    description: "Grade mensal com destaque do dia atual, navegação de meses e estilo folhinha clássica do Windows.",
    defaultWidth: 260,
    defaultHeight: 270,
    minWidth: 220,
    minHeight: 230,
    resizable: true,
    tags: ["calendário", "mês", "dias", "agenda", "data", "compromissos"],
  },
  {
    type: "weather",
    name: "Clima & Previsão",
    category: "utilities",
    icon: "🌤️",
    description: "Temperatura atual, sensação térmica, umidade, vento e ícone dinâmico do tempo da sua cidade.",
    defaultWidth: 280,
    defaultHeight: 190,
    minWidth: 220,
    minHeight: 150,
    resizable: true,
    tags: ["clima", "tempo", "previsão", "temperatura", "chuva", "sol"],
  },
  {
    type: "sticky-notes",
    name: "Notas Rápidas (Post-it)",
    category: "productivity",
    icon: "📝",
    description: "Lembretes e recados carinhosos com cores de post-it fofas, salvamento automático e modo to-do list.",
    defaultWidth: 260,
    defaultHeight: 250,
    minWidth: 200,
    minHeight: 180,
    resizable: true,
    tags: ["notas", "post-it", "lembrete", "recados", "to-do", "tarefas"],
  },
  {
    type: "shortcuts",
    name: "Atalhos & Lançador",
    category: "productivity",
    icon: "🚀",
    description: "Acesso de 1 clique para seus jogos favoritos (Roblox!), navegador, pastas e apps preferidos.",
    defaultWidth: 280,
    defaultHeight: 220,
    minWidth: 220,
    minHeight: 160,
    resizable: true,
    tags: ["atalhos", "roblox", "lançador", "apps", "links", "rápido"],
  },
  {
    type: "cpu-meter",
    name: "Medidor de CPU",
    category: "system",
    icon: "⚡",
    description: "Tacômetro velocímetro clássico do Windows 7 exibindo o uso de processamento em tempo real.",
    defaultWidth: 240,
    defaultHeight: 220,
    minWidth: 190,
    minHeight: 180,
    resizable: true,
    tags: ["cpu", "processador", "sistema", "desempenho", "hardware"],
  },
  {
    type: "ram-meter",
    name: "Medidor de Memória RAM",
    category: "system",
    icon: "🧠",
    description: "Monitoramento de consumo de memória física (GB em uso vs Total) e porcentagem em tempo real.",
    defaultWidth: 240,
    defaultHeight: 220,
    minWidth: 190,
    minHeight: 180,
    resizable: true,
    tags: ["ram", "memória", "desempenho", "sistema", "hardware"],
  },
  {
    type: "storage-meter",
    name: "Discos & Armazenamento",
    category: "system",
    icon: "💾",
    description: "Espaço livre e total dos discos (C:, D:) com barras de capacidade e alertas de pouco espaço.",
    defaultWidth: 280,
    defaultHeight: 180,
    minWidth: 220,
    minHeight: 140,
    resizable: true,
    tags: ["disco", "armazenamento", "ssd", "hd", "espaço", "capacidade"],
  },
  {
    type: "battery-meter",
    name: "Monitor de Bateria",
    category: "system",
    icon: "🔋",
    description: "Percentual de bateria, status de carregamento na tomada ou indicador de alimentação AC desktop.",
    defaultWidth: 240,
    defaultHeight: 170,
    minWidth: 190,
    minHeight: 130,
    resizable: true,
    tags: ["bateria", "energia", "notebook", "desktop", "carregador"],
  },
];

export function getWidgetDefinition(type: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((w) => w.type === type);
}
