import { WidgetDefinition } from "./types";

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  {
    type: "analog-clock",
    name: "Relógio Analógico",
    category: "time",
    icon: "🕐",
    description: "Mostrador circular clássico estilo Windows 7 Gadget, ponteiros suaves e opções de temas.",
    defaultWidth: 240,
    defaultHeight: 240,
    minWidth: 180,
    minHeight: 180,
    resizable: true,
    tags: ["relógio", "tempo", "aero", "ponteiros", "gadget", "horas"],
  },
  {
    type: "digital-clock",
    name: "Relógio Digital & Data",
    category: "time",
    icon: "⏰",
    description: "Horário em números grandes, segundos em tempo real, dia da semana e data completa em português.",
    defaultWidth: 260,
    defaultHeight: 140,
    minWidth: 200,
    minHeight: 100,
    resizable: true,
    tags: ["relógio", "digital", "data", "calendário", "tempo", "segundos"],
  },
  {
    type: "calendar",
    name: "Calendário Folhinha",
    category: "time",
    icon: "📅",
    description: "Grade mensal com destaque do dia atual, navegação de meses e estilo folhinha clássica do Windows.",
    defaultWidth: 260,
    defaultHeight: 270,
    minWidth: 220,
    minHeight: 230,
    resizable: true,
    tags: ["calendário", "mês", "dias", "agenda", "data", "compromissos"],
  },
  {
    type: "weather",
    name: "Clima & Previsão",
    category: "utilities",
    icon: "🌤️",
    description: "Temperatura atual, sensação térmica, umidade, vento e ícone dinâmico do tempo da sua cidade.",
    defaultWidth: 280,
    defaultHeight: 190,
    minWidth: 220,
    minHeight: 150,
    resizable: true,
    tags: ["clima", "tempo", "previsão", "temperatura", "chuva", "sol"],
  },
  {
    type: "sticky-notes",
    name: "Notas Rápidas (Post-it)",
    category: "productivity",
    icon: "📝",
    description: "Lembretes e recados carinhosos com cores de post-it fofas, salvamento automático e modo to-do list.",
    defaultWidth: 260,
    defaultHeight: 250,
    minWidth: 200,
    minHeight: 180,
    resizable: true,
    tags: ["notas", "post-it", "lembrete", "recados", "to-do", "tarefas"],
  },
  {
    type: "shortcuts",
    name: "Atalhos & Lançador",
    category: "productivity",
    icon: "🚀",
    description: "Acesso de 1 clique para seus jogos favoritos (Roblox!), navegador, pastas e apps preferidos.",
    defaultWidth: 280,
    defaultHeight: 220,
    minWidth: 220,
    minHeight: 160,
    resizable: true,
    tags: ["atalhos", "roblox", "lançador", "apps", "links", "rápido"],
  },
  {
    type: "cpu-meter",
    name: "Medidor de CPU",
    category: "system",
    icon: "⚡",
    description: "Tacômetro velocímetro clássico do Windows 7 exibindo o uso de processamento em tempo real.",
    defaultWidth: 240,
    defaultHeight: 220,
    minWidth: 190,
    minHeight: 180,
    resizable: true,
    tags: ["cpu", "processador", "sistema", "desempenho", "hardware"],
  },
  {
    type: "ram-meter",
    name: "Medidor de Memória RAM",
    category: "system",
    icon: "🧠",
    description: "Monitoramento de consumo de memória física (GB em uso vs Total) e porcentagem em tempo real.",
    defaultWidth: 240,
    defaultHeight: 220,
    minWidth: 190,
    minHeight: 180,
    resizable: true,
    tags: ["ram", "memória", "desempenho", "sistema", "hardware"],
  },
  {
    type: "storage-meter",
    name: "Discos & Armazenamento",
    category: "system",
    icon: "💾",
    description: "Espaço livre e total dos discos (C:, D:) com barras de capacidade e alertas de pouco espaço.",
    defaultWidth: 280,
    defaultHeight: 180,
    minWidth: 220,
    minHeight: 140,
    resizable: true,
    tags: ["disco", "armazenamento", "ssd", "hd", "espaço", "capacidade"],
  },
  {
    type: "battery-meter",
    name: "Monitor de Bateria",
    category: "system",
    icon: "🔋",
    description: "Percentual de bateria, status de carregamento na tomada ou indicador de alimentação AC desktop.",
    defaultWidth: 240,
    defaultHeight: 170,
    minWidth: 190,
    minHeight: 130,
    resizable: true,
    tags: ["bateria", "energia", "notebook", "desktop", "carregador"],
  },
  {
    type: "pomodoro",
    name: "Pomodoro Foco & Pausa",
    category: "productivity",
    icon: "🍅",
    description: "Cronômetro com ciclos de foco de 25 min, pausas curtas e longas, sino sonoro e contador de sessões.",
    defaultWidth: 240,
    defaultHeight: 240,
    minWidth: 200,
    minHeight: 200,
    resizable: true,
    tags: ["pomodoro", "foco", "estudo", "trabalho", "tempo", "produtividade"],
  },
  {
    type: "countdown",
    name: "Contagem Regressiva",
    category: "time",
    icon: "🎉",
    description: "Contador de dias, horas e segundos para aniversários, viagens, datas comemorativas e metas.",
    defaultWidth: 260,
    defaultHeight: 180,
    minWidth: 210,
    minHeight: 150,
    resizable: true,
    tags: ["contagem", "evento", "aniversário", "viagem", "tempo", "dias"],
  },
  {
    type: "love-quotes",
    name: "Frases de Amor & Carinho",
    category: "utilities",
    icon: "💌",
    description: "Mensagens doces, afirmações positivas e recadinhos fofos com opção de adicionar frases personalizadas.",
    defaultWidth: 260,
    defaultHeight: 180,
    minWidth: 210,
    minHeight: 140,
    resizable: true,
    tags: ["frases", "amor", "carinho", "motivação", "mensagens", "fofo"],
  },
  {
    type: "photo-frame",
    name: "Porta-Retrato Polaroid",
    category: "utilities",
    icon: "🖼️",
    description: "Exiba sua foto favorita na área de trabalho em uma moldura estilo Polaroid com legenda e fita washi tape.",
    defaultWidth: 240,
    defaultHeight: 270,
    minWidth: 190,
    minHeight: 220,
    resizable: true,
    tags: ["foto", "polaroid", "imagem", "porta-retrato", "lembrança", "memória"],
  },
  {
    type: "world-clock",
    name: "Relógio Mundial",
    category: "time",
    icon: "🌐",
    description: "Fusos horários de cidades do mundo (Brasília, Tóquio, Nova York, Londres) com indicador de dia e noite.",
    defaultWidth: 260,
    defaultHeight: 200,
    minWidth: 220,
    minHeight: 160,
    resizable: true,
    tags: ["relógio", "mundial", "fusos", "tóquio", "londres", "internacional"],
  },
  {
    type: "volume-meter",
    name: "Medidor & Controle de Áudio",
    category: "system",
    icon: "🎚️",
    description: "Visualizador de áudio estilo equalizador VU meter com slider de volume, mute rápido e gerador de notas suaves.",
    defaultWidth: 260,
    defaultHeight: 180,
    minWidth: 220,
    minHeight: 150,
    resizable: true,
    tags: ["volume", "áudio", "som", "equalizador", "mudo", "música"],
  },
  {
    type: "calculator",
    name: "Calculadora Desktop",
    category: "productivity",
    icon: "🧮",
    description: "Calculadora de alta precisão com suporte a teclado físico, visor aero glass e operações rápidas.",
    defaultWidth: 240,
    defaultHeight: 280,
    minWidth: 200,
    minHeight: 240,
    resizable: true,
    tags: ["calculadora", "contas", "matemática", "números", "produtividade"],
  },
  {
    type: "crypto-currency",
    name: "Cotações & Criptomoedas",
    category: "utilities",
    icon: "📈",
    description: "Cotação em tempo real de Dólar, Euro, Bitcoin e Ethereum com conversor instantâneo de Reais (R$).",
    defaultWidth: 280,
    defaultHeight: 230,
    minWidth: 240,
    minHeight: 180,
    resizable: true,
    tags: ["cotação", "dólar", "bitcoin", "moeda", "cripto", "economia", "euro"],
  },
  {
    type: "rss-news",
    name: "Notícias & Manchetes",
    category: "utilities",
    icon: "📰",
    description: "Feed ao vivo de manchetes e tecnologia, games e notícias gerais com carrossel dinâmico.",
    defaultWidth: 280,
    defaultHeight: 220,
    minWidth: 240,
    minHeight: 170,
    resizable: true,
    tags: ["notícias", "feed", "rss", "manchetes", "games", "tecnologia"],
  },
  {
    type: "hydration-reminder",
    name: "Lembrete de Água",
    category: "utilities",
    icon: "💧",
    description: "Acompanhe sua meta diária de hidratação com copinho animado, metas em ml e sino suave de intervalo.",
    defaultWidth: 260,
    defaultHeight: 200,
    minWidth: 220,
    minHeight: 160,
    resizable: true,
    tags: ["água", "saúde", "hidratação", "lembrete", "bem-estar"],
  },
  {
    type: "ambient-audio",
    name: "Sons da Natureza & Lofi",
    category: "utilities",
    icon: "🎧",
    description: "Gerador de ruídos relaxantes da natureza (chuva, ondas, lareira, vento) 100% sintetizado e offline.",
    defaultWidth: 260,
    defaultHeight: 220,
    minWidth: 220,
    minHeight: 180,
    resizable: true,
    tags: ["sons", "chuva", "lofi", "relax", "natureza", "concentração", "dormir"],
  },
  {
    type: "desktop-shelf",
    name: "Prateleira da Área de Trabalho",
    category: "productivity",
    icon: "🪵",
    description: "Estante charmosa com arrasto e soltura (Drag & Drop) de atalhos do Windows, decorações fofas e temas customizáveis.",
    defaultWidth: 320,
    defaultHeight: 180,
    minWidth: 260,
    minHeight: 150,
    resizable: true,
    tags: ["prateleira", "estante", "atalhos", "arquivos", "drag and drop", "organização", "madeira"],
  },
  {
    type: "spotify",
    name: "Spotify Player Desktop",
    category: "utilities",
    icon: "🟢",
    description: "Player oficial de músicas do Spotify na área de trabalho com controle de faixas, capa de álbum com disco de vinil e integração via Firefox.",
    defaultWidth: 320,
    defaultHeight: 250,
    minWidth: 260,
    minHeight: 180,
    resizable: true,
    tags: ["spotify", "música", "player", "som", "álbum", "áudio", "firefox"],
  },
  {
    type: "youtube-music",
    name: "YouTube Music Desktop",
    category: "utilities",
    icon: "🔴",
    description: "Mini player dedicado ao YouTube Music com busca rápida de faixas, capa de álbum, controles de reprodução e atalhos de gêneros.",
    defaultWidth: 320,
    defaultHeight: 260,
    minWidth: 260,
    minHeight: 180,
    resizable: true,
    tags: ["youtube", "music", "música", "player", "streaming", "áudio"],
  },
  {
    type: "youtube",
    name: "YouTube Vídeos & Mini Player",
    category: "utilities",
    icon: "📺",
    description: "Assista a vídeos do YouTube e lives relaxantes de Lofi diretamente em uma janelinha compacta na sua área de trabalho.",
    defaultWidth: 340,
    defaultHeight: 250,
    minWidth: 280,
    minHeight: 210,
    resizable: true,
    tags: ["youtube", "vídeo", "player", "lofi", "streaming", "mini player"],
  },
];

export function getWidgetDefinition(type: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((w) => w.type === type);
}
